### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by RapidfireCRH** [RapidfireCRH/EDDNListdldr---WIP#1]
- [ ] Cleanup args and set toggle flags as necessary
- [ ] store rewritten names as variables so they do not need double processing
- [ ] more comprehensive error log
